<a href="https://colab.research.google.com/github/DevChorong/Supervised-Learning/blob/master/0)_Numpy_%26_Pandas_lib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 0. Data-Processing Libraries
******
## 0-1. Numpy
### # What is Numpy?
- for Processing the Data by the array


### 1. Call the Numpy

In [0]:
import numpy as np # import Numpy before use

### 2. Define Array and Use Numpy

In [0]:
import numpy as np

data1 = [1,2,3,4,5] # define 'Data' - list
print(data1)

print(type(data1)) # check it is list

[1, 2, 3, 4, 5]
<class 'list'>


In [0]:
import numpy as np

data2 = [6,7,8,9,10,11,12] # define 'Data' - list
print(data2)

print(type(data2)) # check it is list

[6, 7, 8, 9, 10, 11, 12]
<class 'list'>


###<mark> # Important!</mark>
before we starting use Numpy
we must define 'list' to 'Numpy Array'<br>
'Numpy Array' is a new type that belong to Numpy lib

In [0]:
import numpy as np

data1 = [1,2,3,4,5]
data2 = [6,7,8,9,10,11,12]

array1 = np.array(data1) # define 'Array' - numpy.ndarray
print(array1)

print(type(array1))  # check it is 'numpy array'
print(array1.dtype) # check it's Data Type
print(array1.shape) # check shape of this Array

[1 2 3 4 5]
<class 'numpy.ndarray'>
int64
(5,)


### # (1)Command that Define Array
> 1. <marK>newValue = np.array(list-Value)</mark>

### # (2)Command that check about Array
> 1. (array).dtype
> 2. (array).shape


### # Let's make 2 Dimention Array

In [0]:
import numpy as np

data = [[1,2,3], [4,5,6], [7,8,9]] # 2 Dimention list

array_2d = np.array(data)
print(array_2d)

print()

print(array_2d.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

(3, 3)


### # (3) How to Masking
Masking( Array Boolean Indexing ) is the Idea<br>
that select the specific row or column what we want

In [0]:
import numpy as np

# the masking Labels
labels = np.array([0,1,2,1,2,0])

# the Data 
data = np.array([['Row0-','A','B','C','D'],['Row1-','E','F','G','H'],['Row2-','I','J','K','L'],['Row3-','M','N','O','P'],['Row4-','Q','R','S','T'],['Row5-','U','V','W','X']])

# make Mask
label_Mask_0 = (labels == 0) # row0 , row5
print(label_Mask_0)

label_Mask_1 = (labels == 1) # row1, row 3
print(label_Mask_1)

label_Mask_2 = (labels == 2) # row2, row 4
print(label_Mask_2)

print()
# select the Data with Masking

print(data[label_Mask_0])
print()


print(data[label_Mask_1])
print()


print(data[label_Mask_2])
print()

# use it with Logical operator

print(data[label_Mask_0 | label_Mask_2]) # row 0, 5 and row 2, 4



[ True False False False False  True]
[False  True False  True False False]
[False False  True False  True False]

[['Row0-' 'A' 'B' 'C' 'D']
 ['Row5-' 'U' 'V' 'W' 'X']]

[['Row1-' 'E' 'F' 'G' 'H']
 ['Row3-' 'M' 'N' 'O' 'P']]

[['Row2-' 'I' 'J' 'K' 'L']
 ['Row4-' 'Q' 'R' 'S' 'T']]

[['Row0-' 'A' 'B' 'C' 'D']
 ['Row2-' 'I' 'J' 'K' 'L']
 ['Row4-' 'Q' 'R' 'S' 'T']
 ['Row5-' 'U' 'V' 'W' 'X']]


******
## 0-2. Pandas
### # what is Pandas?
Pandas deal with data type "Series" , "Data Frame"<br>
we need to use Pandas with Numpy

### 1. Call the Pandas ( & Numpy )


In [0]:
import pandas as pd
import numpy as np

### 2. Define Series and Use Pandas

In [0]:
import pandas as pd
import numpy as np

obj = pd.Series([1,2,3,4])
print(obj)

0    1
1    2
2    3
3    4
dtype: int64


### <mark># Important!</mark>
when we define Series it's shape is looks like this<br>

> [index Number] data0 <br>
> [index Number] data1 <br>
> ...<br>
> dtype : ~

so we can use the command like this
> (Series).values<br>
> (Series).index<br>
> (Series).dtypes<br>


In [0]:
import pandas as pd
import numpy as np

obj = pd.Series([1,2,3,4])
print(obj.values)
print(obj.index)
print(obj.dtypes)
print()

# we can change index arbitrarily
obj2 = pd.Series([5,6,7,8], index = ['one','two','three','four'])
print(obj2)
print(obj2.index)

[1 2 3 4]
RangeIndex(start=0, stop=4, step=1)
int64

one      5
two      6
three    7
four     8
dtype: int64
Index(['one', 'two', 'three', 'four'], dtype='object')


******
### 3. Define DataFrame and use Pandas
when define DataFrame we can use Data type<br>
> Dictionary Type<br>
> numpy Array Type

In [11]:
import numpy as np
import pandas as pd

data = {'name' : ['A','B','C','D','E'],'age' : [21, 19, 18, 22, 25], 'score' : [100, 94, 86, 98, 88] }

print(type(data))

df = pd.DataFrame(data)

print(type(df))

print()

print(df.iloc[2]) ## Deal with a Low

print()

print(df['name']) ## Deal with a Column



<class 'dict'>
<class 'pandas.core.frame.DataFrame'>

name      C
age      18
score    86
Name: 2, dtype: object

0    A
1    B
2    C
3    D
4    E
Name: name, dtype: object
